apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  name: rcgehphkgo-www-ingress
  namespace: dev
spec:
  rules:
  - host: rcgehphkgo.com
    http:
      paths:
      - backend:
          serviceName: rcgehphkgo-www-service
          servicePort: 80
        path: /
  - host: www.rcgehphkgo.com
    http:
      paths:
      - backend:
          serviceName: rcgehphkgo-www-service
          servicePort: 80
        path: /
  tls:
  - hosts:
    - rcgehphkgo.com
    - www.rcgehphkgo.com
    secretName: rcgehphkgo-www-certificate-secret
